import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
// Run: npm install --no-save @electric-sql/pglite && node supabase/round-safety.test.mjs
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec(`
create table questions(id uuid primary key default gen_random_uuid(),type text default 'binary',prompt text,options jsonb,category text,enabled boolean default true);
create table rooms(id uuid primary key default gen_random_uuid(),code text,phase text default 'lobby',current_question_id uuid,round int default 0);
create table players(id uuid primary key default gen_random_uuid(),room_id uuid references rooms(id),name text,avatar int,joined_at timestamptz default now(),unique(room_id,avatar));
create table answers(id uuid primary key default gen_random_uuid(),room_id uuid references rooms(id),question_id uuid,player_id uuid references players(id) on delete cascade,choice text,comment text,unique(room_id,question_id,player_id));
`);
await db.exec(await readFile(new URL('./round-safety.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('./round-safety.sql',import.meta.url),'utf8'));
let count=0;const test=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
const q=async(sql,args=[]) => (await db.query(sql,args)).rows;
const [r]=await q("insert into rooms(code) values('8236') returning *");
const [qa]=await q("insert into questions(prompt,options) values('测试二选一','[]') returning *");
const [qb]=await q("insert into questions(prompt,options) values('下一题','[]') returning *");
const [rank]=await q("insert into questions(type,prompt,options) values('ranking','排序','[]') returning *");
const join=(name='小熊',avatar=0)=>q('insert into players(room_id,name,avatar) values($1,$2,$3) returning *',[r.id,name,avatar]);
const publish=id=>q("update rooms set phase='answering',current_question_id=$2 where id=$1 returning *",[r.id,id]);
const room=async()=> (await q('select * from rooms where id=$1',[r.id]))[0];
await test('昵称最多四个字',async()=>assert.rejects(join('这是五个字')));
const [p1]=await join('四字昵称',0);const [p2]=await join('小兔',0);
await test('冲突头像重新分配',async()=>assert.notEqual(p1.avatar,p2.avatar));
await test('未开启不能发题',async()=>assert.rejects(publish(qa.id)));
await q("update rooms set phase='ready' where id=$1",[r.id]);
await test('排序题不开放游戏',async()=>assert.rejects(publish(rank.id)));
await publish(qa.id);
await test('发布冻结当前两人',async()=>assert.equal((await room()).round_player_ids.length,2));
const [late]=await join('迟到玩家',4);
const answer=(id,choice='A',comment='')=>q('insert into answers(room_id,question_id,player_id,choice,comment) values($1,$2,$3,$4,$5)',[r.id,qa.id,id,choice,comment]);
await test('迟到不改变当前轮人数',async()=>assert.equal((await room()).round_player_ids.length,2));
await test('迟到玩家不能答当前题',async()=>assert.rejects(answer(late.id)));
await test('必须二选一',async()=>assert.rejects(answer(p1.id,'C')));
await test('评论最多八十字',async()=>assert.rejects(answer(p1.id,'A','字'.repeat(81))));
await answer(p1.id,'B','保留评论');
await test('每人只提交一次',async()=>assert.rejects(answer(p1.id)));
await test('提交后不能改答案',async()=>assert.rejects(q("update answers set choice='A' where player_id=$1",[p1.id])));
await test('尚未答齐不能自动揭晓',async()=>assert.equal((await room()).phase,'answering'));
await test('答题期间不能发下一题',async()=>assert.rejects(publish(qb.id)));
await answer(p2.id);
await test('只按冻结名单自动揭晓',async()=>assert.equal((await room()).phase,'reveal'));
await test('手动重复发布被拒绝',async()=>assert.rejects(publish(qa.id)));
await publish(qb.id);
await test('下一题纳入迟到玩家',async()=>assert.equal((await room()).round_player_ids.length,3));
await test('累计已出题与轮次',async()=>{const r=await room();assert.equal(r.round,2);assert.equal(r.used_question_ids.length,2);});
for(let i=3;i<20;i++)await join('玩家',0);
await test('房间最多二十人',async()=>assert.rejects(join()));
await test('二十个头像没有重复',async()=>assert.equal((await q('select count(distinct avatar)::int n from players'))[0].n,20));
await q('delete from answers where room_id=$1',[r.id]);await q('delete from players where room_id=$1',[r.id]);
await q("update rooms set phase='lobby',current_question_id=null,round=0,used_question_ids='{}',round_player_ids='{}' where id=$1",[r.id]);
await test('清空保留房间码并清除进度',async()=>{const r=await room();assert.equal(r.code,'8236');assert.equal(r.round,0);assert.equal(r.used_question_ids.length,0);assert.equal(r.round_player_ids.length,0);});
await q("update rooms set phase='ended' where id=$1",[r.id]);
await test('已结束的房间不能加入',async()=>assert.rejects(join()));
await db.close();console.log(count+' database checks passed');

