import {useEffect,useMemo,useState} from 'react';import {useParams} from 'react-router-dom';import {motion,AnimatePresence} from 'framer-motion';import {AnimalAvatar} from '../lib/avatars';import {demoQuestions} from '../lib/demo';import {configured,supabase} from '../lib/supabase';
type Stage='join'|'avatar'|'lobby'|'answer'|'waiting'|'reveal';type LivePlayer={id:string;room_id:string;name:string;avatar:number};
export default function Player(){const {code=''}=useParams();const [stage,setStage]=useState<Stage>('join');const [name,setName]=useState('');const [avatar,setAvatar]=useState(0);const [playerId,setPlayerId]=useState('');const [roomId,setRoomId]=useState('');const [livePlayers,setLivePlayers]=useState<LivePlayer[]>([]);const [error,setError]=useState('');const [comment,setComment]=useState('');const [choice,setChoice]=useState('');const q=demoQuestions[0];const players=useMemo(()=>livePlayers.length?livePlayers:[{id:playerId||'me',room_id:roomId,name:name||'你',avatar}], [livePlayers,playerId,roomId,name,avatar]);
const refreshPlayers=async(id:string)=>{if(!supabase)return;const {data}=await supabase.from('players').select('id,room_id,name,avatar').eq('room_id',id).order('joined_at');setLivePlayers((data??[]) as LivePlayer[])};
const join=async()=>{if(!supabase){setError('Supabase 尚未配置');return}const clean=name.trim();if(!clean)return;setError('');const {data:room,error:roomError}=await supabase.from('rooms').select('id,code').eq('code',code).eq('phase','lobby').maybeSingle();if(roomError||!room){setError('房间不存在或已经开始');return}const {data:existing}=await supabase.from('players').select('avatar').eq('room_id',room.id);if((existing?.length??0)>=20){setError('房间已满');return}const used=new Set((existing??[]).map(x=>x.avatar));const free=Array.from({length:20},(_,i)=>i).filter(i=>!used.has(i));if(!free.length){setError('房间已满');return}const assigned=free[Math.floor(Math.random()*free.length)];const {data:p,error:joinError}=await supabase.from('players').insert({room_id:room.id,name:clean,avatar:assigned}).select('id,room_id,name,avatar').single();if(joinError){setError(joinError.code==='23505'?'头像刚被别人抢走了，请再点一次加入':joinError.message);return}setRoomId(room.id);setPlayerId(p.id);setAvatar(p.avatar);setStage('avatar');await refreshPlayers(room.id)};
useEffect(()=>{if(!roomId||!supabase)return;refreshPlayers(roomId);const channel=supabase.channel(`player-${roomId}`).on('postgres_changes',{event:'*',schema:'public',table:'players',filter:`room_id=eq.${roomId}`},()=>refreshPlayers(roomId)).subscribe();return()=>{supabase.removeChannel(channel)}},[roomId]);
useEffect(()=>{if(stage==='waiting'){const t=setTimeout(()=>setStage('reveal'),2200);return()=>clearTimeout(t)}},[stage]);const submit=(c:string)=>{setChoice(c);setStage('waiting')};
if(stage==='join')return <Shell><div className="brand small">二选一</div><section className="white-card"><h2>加入房间</h2><label>房间号<input value={code} readOnly/></label><label>你的名字<input placeholder="输入昵称" value={name} onChange={e=>setName(e.target.value)} maxLength={12}/></label><button className="primary" disabled={!name.trim()||!configured} onClick={join}>加入房间</button>{error&&<p>{error}</p>}</section></Shell>;
if(stage==='avatar')return <Shell><div className="white-card avatar-assign"><h2>欢迎加入！</h2><p>这是你的专属头像</p><AnimalAvatar index={avatar} size={116}/><h2>{name}</h2><button className="primary" onClick={()=>setStage('lobby')}>进入房间</button></div></Shell>;
if(stage==='lobby')return <Shell><Header code={code} round="等待开局"/><div className="avatar-grid">{players.map(p=><div key={p.id}><AnimalAvatar index={p.avatar}/><span>{p.name}</span></div>)}</div><div className="wait-pill">等待房主开始游戏…</div><button className="demo-link" onClick={()=>setStage('answer')}>Demo：开始</button></Shell>;
if(stage==='answer')return <Shell><Header code={code} round="第 3 / 10 题"/><section className="question-card"><div className="must">必须选一个</div><button className="option a" onClick={()=>submit('A')}>{q.options[0].label}</button><b className="vs">VS</b><button className="option b" onClick={()=>submit('B')}>{q.options[1].label}</button><label className="comment-label">💬 我有话说 <span>（可选）</span><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="补一句条件、吐槽或者嘴硬…" maxLength={80}/><small>{comment.length}/80</small></label></section></Shell>;
if(stage==='waiting')return <Shell><Header code={code} round="第 3 / 10 题"/><h1 className="count">{players.length} <small>人在房间</small></h1><Floaters players={players}/><div className="wait-pill">等待其他玩家…<br/><small>所有人选择后自动揭晓</small></div></Shell>;
return <Shell><Header code={code} round="第 3 / 10 题"/><h1 className="reveal-title">揭晓！</h1><div className="reveal-board"><Side side="A" pct="62%" players={players.filter((_,i)=>i%3!==1)} /><Side side="B" pct="38%" players={players.filter((_,i)=>i%3===1)} /></div><AnimatePresence>{comment&&<motion.div className="flying-comment" initial={{x:'100vw',opacity:0}} animate={{x:'-10vw',opacity:[0,1,1,0]}} transition={{duration:5}}><AnimalAvatar index={avatar} size={34}/>{comment}</motion.div>}</AnimatePresence><section className="discussion"><h3>大家有话说</h3>{comment&&<p><AnimalAvatar index={avatar} size={30}/><b>{name}：</b>{comment}</p>}</section></Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="star-bg phone-page"><div className="phone-shell">{children}</div></main>};function Header({code,round}:{code:string,round:string}){return <header className="player-head"><span className="mini-brand">二选一</span><span>{round}</span><span>#{code}</span></header>};function Floaters({players}:{players:any[]}){return <div className="float-zone">{players.map((p,i)=><motion.div key={p.id} className="floater" style={{left:`${12+(i*23)%72}%`,top:`${12+(i*31)%70}%`}} animate={{x:[0,(i%2?12:-10),0],y:[0,(i%3?8:-12),0]}} transition={{duration:3+i*.25,repeat:Infinity,ease:'easeInOut'}}><AnimalAvatar index={p.avatar} size={48}/><span>{p.name}</span></motion.div>)}</div>};function Side({side,pct,players}:{side:string,pct:string,players:any[]}){return <div className={'reveal-side '+side.toLowerCase()}><h2>{side} <strong>{pct}</strong></h2>{players.map((p,i)=><motion.div className="side-player" key={p.id} initial={{x:side==='A'?120:-120,y:-80,opacity:0}} animate={{x:0,y:0,opacity:1}} transition={{delay:i*.12,type:'spring'}}><AnimalAvatar index={p.avatar} size={36}/><span>{p.name}</span></motion.div>)}</div>}
