import {useEffect,useMemo,useState} from 'react';import {useParams} from 'react-router-dom';import {motion,AnimatePresence} from 'framer-motion';import {AnimalAvatar} from '../lib/avatars';import {demoPlayers,demoQuestions} from '../lib/demo';
type Stage='join'|'avatar'|'lobby'|'answer'|'waiting'|'reveal';
export default function Player(){const {code='8236'}=useParams();const [stage,setStage]=useState<Stage>('join');const [name,setName]=useState('');const [avatar]=useState(()=>Math.floor(Math.random()*20));const [comment,setComment]=useState('');const [choice,setChoice]=useState('');const q=demoQuestions[0];const players=useMemo(()=>[...demoPlayers,{id:'me',room_id:'demo',name:name||'你',avatar}], [name,avatar]);
useEffect(()=>{if(stage==='waiting'){const t=setTimeout(()=>setStage('reveal'),2200);return()=>clearTimeout(t)}},[stage]);
const submit=(c:string)=>{setChoice(c);setStage('waiting')};
if(stage==='join')return <Shell><div className="brand small">二选一</div><section className="white-card"><h2>加入房间</h2><label>房间号<input value={code} readOnly/></label><label>你的名字<input placeholder="输入昵称" value={name} onChange={e=>setName(e.target.value)} maxLength={12}/></label><button className="primary" disabled={!name.trim()} onClick={()=>setStage('avatar')}>加入房间</button></section></Shell>;
if(stage==='avatar')return <Shell><div className="white-card avatar-assign"><h2>欢迎加入！</h2><p>这是你的专属头像</p><AnimalAvatar index={avatar} size={116}/><h2>{name}</h2><button className="primary" onClick={()=>setStage('lobby')}>进入房间</button></div></Shell>;
if(stage==='lobby')return <Shell><Header code={code} round="等待开局"/><div className="avatar-grid">{players.map(p=><div key={p.id}><AnimalAvatar index={p.avatar}/><span>{p.name}</span></div>)}</div><div className="wait-pill">等待房主开始游戏…</div><button className="demo-link" onClick={()=>setStage('answer')}>Demo：开始</button></Shell>;
if(stage==='answer')return <Shell><Header code={code} round="第 3 / 10 题"/><section className="question-card"><div className="must">必须选一个</div><button className="option a" onClick={()=>submit('A')}>{q.options[0].label}</button><b className="vs">VS</b><button className="option b" onClick={()=>submit('B')}>{q.options[1].label}</button><label className="comment-label">💬 我有话说 <span>（可选）</span><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="补一句条件、吐槽或者嘴硬…" maxLength={80}/><small>{comment.length}/80</small></label></section></Shell>;
if(stage==='waiting')return <Shell><Header code={code} round="第 3 / 10 题"/><h1 className="count">7 / 8 <small>已选择</small></h1><Floaters players={players}/><div className="wait-pill">等待其他玩家…<br/><small>所有人选择后自动揭晓</small></div></Shell>;
return <Shell><Header code={code} round="第 3 / 10 题"/><h1 className="reveal-title">揭晓！</h1><div className="reveal-board"><Side side="A" pct="62%" players={players.filter((_,i)=>i%3!==1)} /><Side side="B" pct="38%" players={players.filter((_,i)=>i%3===1)} /></div><AnimatePresence>{comment&&<motion.div className="flying-comment" initial={{x:'100vw',opacity:0}} animate={{x:'-10vw',opacity:[0,1,1,0]}} transition={{duration:5}}><AnimalAvatar index={avatar} size={34}/>{comment}</motion.div>}</AnimatePresence><section className="discussion"><h3>大家有话说</h3><p><AnimalAvatar index={0} size={30}/><b>小周：</b>前提是别违法…</p><p><AnimalAvatar index={2} size={30}/><b>Luna：</b>上头才刺激！</p>{comment&&<p><AnimalAvatar index={avatar} size={30}/><b>{name}：</b>{comment}</p>}</section></Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="star-bg phone-page"><div className="phone-shell">{children}</div></main>}
function Header({code,round}:{code:string,round:string}){return <header className="player-head"><span className="mini-brand">二选一</span><span>{round}</span><span>#{code}</span></header>}
function Floaters({players}:{players:any[]}){return <div className="float-zone">{players.map((p,i)=><motion.div key={p.id} className="floater" style={{left:`${12+(i*23)%72}%`,top:`${12+(i*31)%70}%`}} animate={{x:[0,(i%2?12:-10),0],y:[0,(i%3?8:-12),0]}} transition={{duration:3+i*.25,repeat:Infinity,ease:'easeInOut'}}><AnimalAvatar index={p.avatar} size={48}/><span>{p.name}</span></motion.div>)}</div>}
function Side({side,pct,players}:{side:string,pct:string,players:any[]}){return <div className={'reveal-side '+side.toLowerCase()}><h2>{side} <strong>{pct}</strong></h2>{players.map((p,i)=><motion.div className="side-player" key={p.id} initial={{x:side==='A'?120:-120,y:-80,opacity:0}} animate={{x:0,y:0,opacity:1}} transition={{delay:i*.12,type:'spring'}}><AnimalAvatar index={p.avatar} size={36}/><span>{p.name}</span></motion.div>)}</div>}
